include(":LogMeOutHamachi")
include(":GhostMessage")
include(":MoarConfirm")
include(":BDFDB")
include(":AutoServerNotifs")
include(":NoKyzas")
include(":AutoShowSpoilers")
include(":PinIcon")
include(":Quoter")
include(":xkcd")
include(":Fart")
rootProject.name = "AliuPlugins"
