include(":TestJava")
include(":UserTimezones")
include(":GateFix")
include(":TestPlugin")
include(":ChannelLocker")
include(":GhostMessage")
include(":MoarConfirm")
include(":AutoServerNotifs")
include(":NoKyzas")
include(":AutoShowSpoilers")
include(":PinIcon")
include(":Quoter")
include(":xkcd")
include(":Fart")
rootProject.name = "AliuPlugins"
